# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    message_generator_is_random: '%env(bool:MESSAGE_GENERATOR_IS_RANDOM)%'
    my_slugger_is_lower: '%env(bool:MY_SLUGGER_IS_LOWER)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Config de notre generateur de message
    App\Service\MessageGenerator:
        # arguments à transmettre au constructeur
        arguments:
            # on fait appel à un paramètre de service
            $isRandom: '%message_generator_is_random%'

    App\Service\MySlugger:
        arguments:
            $isLower: '%my_slugger_is_lower%'


    App\EventListener\MovieListener:
        tags:
            -
                # 3 options necessaires au fonctionnement
                name: 'doctrine.orm.entity_listener'
                # par défaut, le nom de la méthode = nom de l'event
                event: 'preUpdate'
                entity: 'App\Entity\Movie'
                # on peut indiquer le nom de la méthode si différente de l'event
                method: 'slugify'
            -
                # 3 options necessaires au fonctionnement
                name: 'doctrine.orm.entity_listener'
                # par défaut, le nom de la méthode = nom de l'event
                event: 'prePersist'
                entity: 'App\Entity\Movie'
                # on peut indiquer le nom de la méthode si différente de l'event
                method: 'slugify'